const SmtErrorCodes = Object.freeze({
    VALIDATION: "SMT_VALIDATION_ERROR",
    UNAUTHORIZED: "SMT_UNAUTHORIZED",
    SESSION_EXPIRED: "SMT_SESSION_EXPIRED",
    RATE_LIMIT: "SMT_RATE_LIMIT",
    REQUEST_ERROR: "SMT_REQUEST_ERROR",
    INTERNAL: "SMT_INTERNAL_ERROR",
    API_KEY_UNAUTHORIZED: "API_KEY_UNAUTHORIZED",
  });
  
  module.exports = { SmtErrorCodes };